name: Deploy to Amazon ECS
 
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
 
      # Step 4: Build and tag the Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +%s)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
 
      # Step 5: Push the Docker image to ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ steps.ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ steps.ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
